const contemporaries = [
  "/wiki/Bellini_(cocktail)",
  "/wiki/Black_Russian",
  "/wiki/Bloody_Mary_(cocktail)",
  "/wiki/Caipirinha",
  "/wiki/Champagne_cocktail",
  "/wiki/Corpse_Reviver_(cocktail)#Corpse_Reviver_№2_&_№2A",
  "/wiki/Cosmopolitan_(cocktail)",
  "/wiki/Cuba_libre",
  "/wiki/French_75_(cocktail)",
  "/wiki/French_Connection_(cocktail)",
  "/wiki/Golden_dream_(cocktail)",
  "/wiki/Grasshopper_(cocktail)",
  "/wiki/Hemingway_Special",
  "/wiki/Horse%27s_Neck",
  "/wiki/Irish_coffee",
  "/wiki/Kir_(cocktail)",
  "/wiki/Long_Island_iced_tea",
  "/wiki/Mai_Tai",
  "/wiki/Margarita",
  "/wiki/Mimosa_(cocktail)",
  "/wiki/Mint_julep",
  "/wiki/Mojito",
  "/wiki/Moscow_mule",
  "/wiki/Pi%C3%B1a_Colada",
  "/wiki/Pisco_Sour",
  "/wiki/Sea_Breeze_(cocktail)",
  "/wiki/Sex_on_the_Beach",
  "/wiki/Singapore_Sling",
  "/wiki/Tequila_Sunrise_(cocktail)",
  "/wiki/Vesper_(cocktail)",
  "/wiki/Zombie_(cocktail)",
];

module.exports = contemporaries;
