const newEra = [
  "/wiki/Barracuda_(cocktail)",
  "/wiki/Bee%27s_Knees_(cocktail)",
  "/wiki/Bramble_(cocktail)",
  "/wiki/Canchanchara",
  "/wiki/Dark_%27n%27_Stormy",
  "/wiki/Espresso_martini",
  "/wiki/Fernandito",
  "/wiki/French_martini",
  "/wiki/Illegal_(cocktail)",
  "/wiki/Lemon_drop_martini",
  "/wiki/Naked_and_Famous_(cocktail)",
  "/wiki/New_York_Sour",
  "/wiki/Old_Cuban",
  "/wiki/Paloma_(cocktail)",
  "/wiki/Paper_Plane_(cocktail)",
  "/wiki/Penicillin_(cocktail)",
  "/wiki/Russian_Spring_Punch",
  "/wiki/Southside_(cocktail)",
  "/wiki/Spicy_Fifty",
  "/wiki/Spritz_Veneziano",
  "/wiki/Suffering_Bastard",
  "/wiki/Tipperary_(cocktail)",
  "/wiki/Tommy%27s_margarita",
  "/wiki/Trinidad_Sour",
  "/wiki/Ve.n.to",
  "/wiki/Yellow_Bird_(cocktail)",
];

module.exports = newEra;
