const unforgettables = [
  "/wiki/Alexander_(cocktail)",
  "/wiki/Americano_(cocktail)",
  "/wiki/Angel_Face_(cocktail)",
  "/wiki/Aviation_(cocktail)",
  "/wiki/Between_the_Sheets_(cocktail)",
  "/wiki/Boulevardier_(cocktail)",
  "/wiki/Brandy_Crusta",
  "/wiki/Casino_(cocktail)",
  "/wiki/Clover_Club_Cocktail",
  "/wiki/Daiquiri",
  "/wiki/Martini_(cocktail)",
  "/wiki/Fizz_(cocktail)#Gin_fizz",
  "/wiki/Hanky_Panky_(cocktail)",
  "/wiki/John_Collins_(cocktail)",
  "/wiki/Last_Word_(cocktail)",
  "/wiki/Manhattan_(cocktail)",
  "/wiki/Martinez_(cocktail)",
  "/wiki/Mary_Pickford_(cocktail)",
  "/wiki/Monkey_Gland",
  "/wiki/Negroni",
  "/wiki/Old_fashioned_(cocktail)",
  "/wiki/Paradise_(cocktail)",
  "/wiki/Planter%27s_Punch",
  "/wiki/Porto_flip",
  "/wiki/Fizz_(cocktail)#Ramos_gin_fizz",
  "/wiki/Rusty_Nail_(cocktail)",
  "/wiki/Sazerac",
  "/wiki/Sidecar_(cocktail)",
  "/wiki/Stinger_(cocktail)",
  "/wiki/Tuxedo_(cocktail)",
  "/wiki/Vieux_Carr%C3%A9_(cocktail)",
  "/wiki/Whiskey_sour",
  "/wiki/Sour_(cocktail)#White_Lady",
];

module.exports = unforgettables;
