module.exports = [
  {
    title: "Alexander",
    image: "/wiki/File:Alexander_Cocktail.png",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Nutmeg",
    preparation:
      "Shake all ingredients with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.",
    timing: "After dinner",
    category: "The Unforgettables",
    src: "/wiki/Alexander_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Cognac", "Crème de cacao"],
    ingredients: [
      "3 cl cognac",
      "3 cl brown crème de cacao",
      "3 cl light cream",
    ],
  },
  {
    title: "Americano",
    image: "/wiki/File:Americano_cocktail_at_Nightwood_Restaurant.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "half an orange slice, lemon twist",
    preparation:
      "Pour the Campari and vermouth over ice into a highball glass, add a splash of soda water and garnish with half orange slice and a lemon twist.",
    timing: "Before dinner",
    category: "The Unforgettables",
    src: "/wiki/Americano_(cocktail)",
    drinkware: "Highball glass",
    alcohol: ["Vermouth", "Campari"],
    ingredients: [
      "3 cl Campari",
      "3 cl red vermouth",
      "A splash of soda water",
    ],
  },
  {
    title: "Angel Face",
    image: "/wiki/File:IBA_Cocktail_Angel_Face_(28068833805).jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.",
    timing: "All day",
    category: "The Unforgettables",
    src: "/wiki/Angel_Face_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin", "Calvados"],
    ingredients: ["3 cl gin", "3 cl Apricot brandy", "3 cl Calvados"],
  },
  {
    title: "Aviation",
    image: "/wiki/File:Aviation_Cocktail.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "cherry",
    preparation:
      "Add all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass. Garnish with a cherry.",
    timing: "All day",
    category: "The Unforgettables",
    src: "/wiki/Aviation_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: [
      "45 ml gin",
      "15 ml lemon juice",
      "15 ml maraschino liqueur",
      "1 barspoon crème de violette",
    ],
  },
  {
    title: "Between the Sheets",
    image: "/wiki/File:Between_The_Sheets_Cocktail.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour all ingredients into shaker with ice cubes, shake, strain into chilled cocktail glass.",
    timing: "All Day",
    category: "The Unforgettables",
    src: "/wiki/Between_the_Sheets_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Cognac", "Rum", "Triple sec"],
    ingredients: [
      "3 cl white rum",
      "3 cl cognac",
      "3 cl triple sec",
      "2 cl fresh lemon juice",
    ],
  },
  {
    title: "Boulevardier",
    image: "/wiki/File:Society_Lounge_-_Boulevardier_-_16164913902.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Orange peel or cherry",
    preparation: "Stir with ice, strain, garnish and serve.",
    category: "The Unforgettables",
    src: "/wiki/Boulevardier_(cocktail)",
    drinkware: "Old Fashioned glass",
    alcohol: ["Bourbon whiskey", "Vermouth", "Campari"],
    ingredients: [
      "30 ml (1 part) or 45 ml (1.5 parts) bourbon",
      "30 ml (1 part) sweet red vermouth",
      "30 ml (1 part) campari",
    ],
  },
  {
    title: "Casino",
    image: "/wiki/File:Casino_Cocktail_(9120690108).jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Lemon twist and maraschino cherry",
    preparation:
      "Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass. Garnish with a lemon twist and a maraschino cherry. Serve without a straw.",
    timing: "All Day",
    category: "The Unforgettables",
    src: "/wiki/Casino_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: [
      "4 cl gin (Old Tom)",
      "1 cl Maraschino",
      "1 cl fresh lemon juice",
      "2 dashes orange bitters",
    ],
  },
  {
    title: "Clover Club Cocktail",
    image: "/wiki/File:Cloverclub.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Dry shake ingredients to emulsify, add ice, shake and served straight up.",
    timing: "All Day",
    category: "The Unforgettables",
    src: "/wiki/Clover_Club_Cocktail",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: [
      "4.5cl Gin",
      "1.5cl lemon juice",
      "1.5cl raspberry syrup",
      "1 egg white",
    ],
  },
  {
    title: "Daiquiri",
    image: "/wiki/File:Classic_Daiquiri_in_Cocktail_Glass.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "In a cocktail shaker add all ingredients. Stir well to dissolve the sugar. Add ice and shake. Strain into chilled cocktail glass.",
    timing: "Happy Hour / Summer drink",
    category: "The Unforgettables",
    src: "/wiki/Daiquiri",
    drinkware: "Cocktail glass",
    alcohol: ["Rum"],
    ingredients: [
      "6 cl white rum",
      "2 cl lime juice",
      "2 bar spoons superfine sugar",
    ],
  },
  {
    title: "Dry Martini",
    image: "/wiki/File:15-09-26-RalfR-WLC-0084.jpg",
    type: "Cocktail",
    served: "Up (or on the rocks)",
    "standard-garnish": "Olive or lemon twist",
    preparation:
      "Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.",
    timing: "Before dinner",
    category: "The Unforgettables",
    src: "/wiki/Martini_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: ["6 cl (6 parts) gin", "1 cl (1 parts) dry vermouth"],
  },
  {
    title: "Hanky Panky",
    image: "/wiki/File:Hanky_Panky_cocktail.jpg",
    type: "Mixed drink",
    served: "up",
    "standard-garnish": "Orange zest",
    preparation:
      "Stirred over ice, strained into a chilled glass, garnished, and served up.",
    category: "The Unforgettables",
    src: "/wiki/Hanky_Panky_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin", "Vermouth"],
    ingredients: [
      "45 ml London Dry Gin",
      "45 ml Sweet Red Vermouth",
      "7.5 ml Fernet Branca",
    ],
  },
  {
    title: "John Collins",
    image: "/wiki/File:IBA_Cocktail_John_Collins_(29221732881).jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Lemon slice and maraschino cherry",
    preparation:
      "Pour all ingredients directly into highball glass filled with ice. Stir gently. Garnish. Add a dash of Angostura bitters.",
    category: "The Unforgettables",
    src: "/wiki/John_Collins_(cocktail)",
    drinkware: "Collins glass",
    alcohol: ["Gin"],
    ingredients: [
      "4.5 cl (3 parts) gin",
      "3 cl (2 parts) freshly squeezed lemon juice",
      "1.5 cl (1 part) sugar syrup",
      "6 cl (4 parts) carbonated water",
    ],
  },
  {
    title: "The Last Word",
    image: "/wiki/File:The_Last_Word_cocktail_raised.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation: "Shake with ice and strain into a cocktail glass.",
    category: "The Unforgettables",
    src: "/wiki/Last_Word_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["green Chartreuse"],
    ingredients: [
      "One part gin",
      "One part lime juice",
      "One part green Chartreuse",
      "One part maraschino liqueur",
    ],
  },
  {
    title: "Manhattan",
    image: "/wiki/File:Manhattan_Cocktail2.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Luxardo cherry",
    preparation:
      "Stirred over ice, strained into a chilled glass, garnished, and served up.",
    timing: "Before Dinner",
    category: "The Unforgettables",
    src: "/wiki/Manhattan_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Whiskey"],
    ingredients: [
      "5 cL Rye whiskey",
      "2 cL Sweet red vermouth",
      "Dash Angostura bitters",
    ],
  },
  {
    title: "Martinez",
    image: "/wiki/File:Martinez_Cocktail.jpg",
    type: "Cocktail",
    served: "up",
    "standard-garnish": "lemon zest",
    preparation:
      "Stirred over ice, strained into a chilled glass, garnished, and served up.",
    category: "The Unforgettables",
    src: "/wiki/Martinez_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: [
      "45 ml London Dry Gin",
      "45 ml Sweet Red Vermouth",
      "1 Bar Spoon Maraschino Liqueur",
      "2 Dashes Orange Bitters",
    ],
  },
  {
    title: "Mary Pickford",
    image: "/wiki/File:Mary_Pickford_Cocktail.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation: "Shake and strain into a chilled large cocktail glass",
    timing: "All Day",
    category: "The Unforgettables",
    src: "/wiki/Mary_Pickford_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Rum"],
    ingredients: [
      "6 cl white rum",
      "6 cl fresh pineapple juice",
      "1 cl Grenadine",
      "1 cl Maraschino",
    ],
  },
  {
    title: "Monkey Gland",
    image: "/wiki/File:Monkey_Gland_(11677703163).jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Shake well over ice cubes in a shaker, strain into a chilled cocktail glass.",
    timing: "All Day",
    category: "The Unforgettables",
    src: "/wiki/Monkey_Gland",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: [
      "5cl gin",
      "3cl orange juice",
      "2 drops absinthe",
      "2 drops grenadine",
    ],
  },
  {
    title: "Negroni",
    image: "/wiki/File:Negroni_served_in_Vancouver_BC.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Orange slice",
    preparation: "Stir into glass over ice, garnish and serve.",
    timing: "Before dinner",
    category: "The Unforgettables",
    src: "/wiki/Negroni",
    drinkware: "Old Fashioned glass",
    alcohol: ["Gin", "Vermouth", "Campari"],
    ingredients: ["3 cl gin", "3 cl sweet red vermouth", "3 cl Campari"],
  },
  {
    title: "Old Fashioned",
    image: "/wiki/File:Whiskey_Old_Fashioned1.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Orange twist or cocktail cherry",
    preparation:
      "Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey. Garnish with orange twist, and a cocktail cherry.",
    timing: "Before dinner",
    category: "The Unforgettables",
    src: "/wiki/Old_fashioned_(cocktail)",
    drinkware: "Old Fashioned glass",
    alcohol: ["Whiskey"],
    ingredients: [
      "4.5 cl Bourbon or Rye whiskey",
      "2 dashes Angostura bitters",
      "1 sugar cube",
      "Few dashes plain water",
    ],
  },
  {
    title: "Paradise",
    image: "/wiki/File:Question_book-new.svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Shake together over ice. Strain into cocktail glass and serve chilled.",
    timing: "All Day",
    category: "The Unforgettables",
    src: "/wiki/Paradise_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: [
      "3.5 cl (7 parts) gin",
      "2 cl (4 parts) apricot brandy",
      "1.5 cl (3 parts) orange juice",
    ],
  },
  {
    title: "Planter's punch",
    image: "/wiki/File:Planters_Punch_2.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Cherry and pineapple slice",
    preparation:
      "Pour all ingredients, except the bitters, into shaker filled with ice. Shake well. Pour into large glass, filled with ice. Add dash Angostura bitters. Garnish with cocktail cherry and pineapple.",
    category: "The Unforgettables",
    src: "/wiki/Planter%27s_Punch",
    drinkware: "Highball glass",
    alcohol: ["Rum"],
    ingredients: [
      "4.5cl Dark rum",
      "3.5 cl fresh orange juice",
      "3.5 cl fresh pineapple juice",
      "2 cl fresh lemon juice",
      "1 cl Grenadine syrup",
      "1 cl simple syrup",
      "3 or 4 dashes Angostura bitters",
    ],
  },
  {
    title: "Porto Flip",
    image: "/wiki/File:Question_book-new.svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Grated nutmeg",
    preparation:
      "Shake ingredients together in a mixer with ice. Strain into glass, garnish and serve",
    timing: "After Dinner",
    category: "The Unforgettables",
    src: "/wiki/Porto_flip",
    drinkware: "Cocktail glass",
    alcohol: ["Port"],
    ingredients: [
      "1.5 cl (3 parts) brandy",
      "4.5 cl (9 parts) port",
      "1 cl (2 parts) egg yolk",
    ],
  },
  {
    title: "Rusty Nail",
    image:
      "/wiki/File:Rusty_Nail_a_cocktail_by_@tokenchick13_(16503594826).jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Lemon twist",
    preparation:
      "Pour all ingredients directly into old-fashioned glass filled with ice. Stir gently. Garnish with a lemon twist. Serve.",
    timing: "After Dinner",
    category: "The Unforgettables",
    src: "/wiki/Rusty_Nail_(cocktail)",
    drinkware: "Old Fashioned glass",
    alcohol: ["Scotch whisky"],
    ingredients: ["4.5 cl Scotch Whisky", "2.5 cl Drambuie"],
  },
  {
    title: "Sazerac",
    image: "/wiki/File:SazeracRooseveltNOLA1July2009.JPG",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Lemon peel",
    preparation:
      "Rinse a chilled old-fashioned glass with the absinthe, add crushed ice, and set it aside. Stir the remaining ingredients over ice and set it aside. Discard the ice and any excess absinthe from the prepared glass, and strain the drink into the glass. Add the lemon peel for garnish.[1]",
    timing: "After dinner",
    notes:
      "Note: The original recipe changed in the latter part of the 19th century. Rye whiskey was substituted when cognac became difficult to obtain.[2]",
    category: "The Unforgettables",
    src: "/wiki/Sazerac",
    drinkware: "Old Fashioned glass",
    alcohol: ["Cognac"],
    ingredients: [
      "5 cl cognac",
      "1 cl absinthe",
      "One sugar cube",
      "Two dashes Peychaud's Bitters",
    ],
  },
  {
    title: "Sidecar",
    image: "/wiki/File:Sidecar-cocktail.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass.",
    timing: "All Day",
    category: "The Unforgettables",
    src: "/wiki/Sidecar_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Cognac"],
    ingredients: ["5 cl cognac", "2 cl triple sec", "2 cl lemon juice"],
  },
  {
    title: "Stinger",
    image: "/wiki/File:Stinger_Cocktail.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour in a mixing glass with ice, stir and strain into a cocktail glass. May also be served on rocks in a rocks glass.",
    timing: "After Dinner (Before Dinner)",
    notes:
      "It has been suggested that during the 1920s the Stinger ceased being an after-dinner cocktail, and instead should be consumed before dinner.[1] However, the IBA continues to list the Stinger as an after-dinner cocktail.[2]",
    category: "The Unforgettables",
    src: "/wiki/Stinger_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Cognac"],
    ingredients: ["5 cL cognac", "2 cL white crème de menthe"],
  },
  {
    title: "Tuxedo",
    image: "/wiki/File:Cocktail_Glass_(Martini).svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "cherry, lemon zest",
    preparation:
      "Stir all ingredients with ice and strain into a cocktail glass. Garnish with a cherry and a twist of lemon zest.",
    timing: "All Day",
    category: "The Unforgettables",
    src: "/wiki/Tuxedo_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: [
      "3 cl gin (Old Tom)",
      "3 cl dry Vermouth",
      "1/2 barspoon Maraschino",
      "1/4 barspoon Absinthe",
      "3 dashes orange bitters",
    ],
  },
  {
    title: "Vieux Carré",
    image: "/wiki/File:Vieux_Carre_Cocktail.jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Orange zest and maraschino cherry",
    preparation:
      "Pour all ingredients into a mixing glass with ice cubes. Stir well. Strain into chilled cocktail glass. Garnish with orange zest and a maraschino cherry.",
    category: "The Unforgettables",
    src: "/wiki/Vieux_Carr%C3%A9_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Rye whiskey", "Cognac", "Vermouth"],
    ingredients: [
      "3 cl rye whiskey",
      "3 cl cognac",
      "3 cl sweet Vermouth",
      "1 barspoon Bénédictine",
      "2 dashes Peychaud's bitters",
    ],
  },
  {
    title: "Whiskey Sour",
    image: "/wiki/File:Whiskey_Sour.jpg",
    type: "Cocktail",
    served: "On the rocks or straight up",
    "standard-garnish": "Maraschino cherry and half orange slice",
    preparation:
      "Shake with ice. Strain into chilled glass, garnish and serve.",
    timing: "Before Dinner",
    notes:
      "If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.",
    category: "The Unforgettables",
    src: "/wiki/Whiskey_sour",
    drinkware: "Old Fashioned glass",
    alcohol: ["Whiskey"],
    ingredients: [
      "4.5 cl (3 parts) bourbon whiskey",
      "3 cl (2 parts) fresh lemon juice",
      "1.5 cl (1 part) simple syrup",
    ],
  },
  {
    title: "Bellini",
    image: "/wiki/File:Bellini_Cipriani,_Macaroni_Grill,_Dunwoody_GA.jpg",
    type: "Wine cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour peach purée into chilled glass, add sparkling wine. Stir gently.",
    notes: "Traditionally a Bellini uses white peaches for the fruit.",
    category: "Contemporary Classics",
    src: "/wiki/Bellini_(cocktail)",
    drinkware: "Champagne flute",
    alcohol: ["Prosecco"],
    ingredients: [
      "10 cl (2 parts) Prosecco",
      "5 cl (1 part) fresh peach purée",
    ],
  },
  {
    title: "Black Russian",
    image: "/wiki/File:Black_Russian.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    preparation:
      "Pour the ingredients into an old fashioned glass filled with ice cubes. Stir gently.",
    timing: "After dinner",
    category: "Contemporary Classics",
    src: "/wiki/Black_Russian",
    drinkware: "Old Fashioned glass",
    alcohol: ["Vodka"],
    ingredients: ["4 cl Vodka", "2 cl Coffee liqueur"],
  },
  {
    title: "Bloody Mary",
    image:
      "/wiki/File:Bloody_Mary_Coctail_with_celery_stalk_-_Evan_Swigart.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Celery stalk and lemon wedge (optional)",
    preparation:
      "Stirring gently, pour all ingredients into highball glass. Garnish.",
    category: "Contemporary Classics",
    src: "/wiki/Bloody_Mary_(cocktail)",
    drinkware: "Highball glass",
    alcohol: ["Vodka"],
    ingredients: [
      "4.5 cl/1 jigger (3 parts) vodka",
      "9 cl/3 oz (6 parts) Tomato juice",
      "1.5 cl/1 tbsp (1 part) Lemon juice",
      "2 to 3 dashes of Worcestershire Sauce",
      "Tabasco sauce",
      "Celery salt",
      "Black pepper",
    ],
  },
  {
    title: "Caipirinha",
    image: "/wiki/File:15-09-26-RalfR-WLC-0048.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "sugarcane, lime(ingredient)",
    preparation:
      "Place lime and sugar into old fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with ice and add the Cachaça.",
    notes:
      "A wide variety of fresh fruits can be used in place of lime. In the absence of cachaça, vodka can be used, making a caipiroska.[1]",
    category: "Contemporary Classics",
    src: "/wiki/Caipirinha",
    drinkware: "Old Fashioned glass",
    alcohol: ["Cachaça"],
    ingredients: [
      "5 cl cachaça",
      "Half a lime cut into 4 wedges",
      "2 teaspoons sugar",
    ],
  },
  {
    title: "Champagne Cocktail",
    image: "/wiki/File:Question_book-new.svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Orange slice and maraschino cherry",
    preparation:
      "Add dash of Angostura bitter onto sugar cube and drop it into champagne flute. Add cognac followed by gently pouring chilled champagne. Garnish with orange slice and maraschino cherry.",
    category: "Contemporary Classics",
    src: "/wiki/Champagne_cocktail",
    drinkware: "Champagne flute",
    alcohol: ["Champagne"],
    ingredients: [
      "9cl Champagne",
      "1cl cognac",
      "2 dashes Angostura bitters",
      "1 sugar cube",
    ],
  },
  {
    title: "Cosmopolitan",
    image: "/wiki/File:Cosmopolitan_(5076906532).jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "lime slice",
    preparation:
      "Shake all ingredients in cocktail shaker filled with ice. Strain into a large cocktail glass. Garnish with lime slice.",
    timing: "All day",
    notes: "The drink should be a frothy bright pink color",
    category: "Contemporary Classics",
    src: "/wiki/Cosmopolitan_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Vodka"],
    ingredients: [
      "4 cl Vodka Citron",
      "1.5 cl Cointreau",
      "1.5 cl Fresh lime juice",
      "3 cl Cranberry juice",
    ],
  },
  {
    title: "Rum and Coke (Cuba libre)",
    image: "/wiki/File:15-09-26-RalfR-WLC-0056.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Lime wedge",
    preparation:
      "Build all ingredients in a highball glass filled with ice. Garnish with lime wedge.",
    category: "Contemporary Classics",
    src: "/wiki/Cuba_libre",
    drinkware: "Highball glass",
    alcohol: ["Rum"],
    ingredients: ["12 cl Cola", "5 cl white rum", "1 cl Fresh lime juice"],
  },
  {
    title: "French 75",
    image: "/wiki/File:French_75.jpg",
    type: "Wine cocktail",
    served: "Straight up; without ice",
    preparation:
      "Combine gin, syrup, and lemon juice in a cocktail shaker filled with ice. Shake vigorously and strain into a chilled champagne glass. Top up with Champagne. Stir gently.",
    category: "Contemporary Classics",
    src: "/wiki/French_75_(cocktail)",
    drinkware: "Champagne flute",
    alcohol: ["Champagne"],
    ingredients: [
      "3 cl gin",
      "2 dashes simple syrup",
      "1.5 cl lemon juice",
      "6 cl Champagne",
    ],
  },
  {
    title: "French Connection",
    image: "/wiki/File:Old_Fashioned_Glass.svg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    preparation:
      "Pour all ingredients directly into old fashioned glass filled with ice cubes. Stir gently.",
    timing: "After dinner",
    category: "Contemporary Classics",
    src: "/wiki/French_Connection_(cocktail)",
    drinkware: "Old Fashioned glass",
    alcohol: ["Cognac"],
    ingredients: ["3.5cl Cognac", "3.5cl Amaretto liqueur"],
  },
  {
    title: "Golden Dream",
    image: "/wiki/File:Godlen-Dream_Mixed_Drink_Cocktail_(2360538105).jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation: "Shake with cracked ice. Strain into glass and serve.",
    timing: "After dinner",
    notes: "Should be quite fluffy",
    category: "Contemporary Classics",
    src: "/wiki/Golden_dream_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Orange-flavored liqueur", "Galliano"],
    ingredients: [
      "2 cl (2 parts) Galliano",
      "2 cl (2 parts) Triple Sec",
      "2 cl (2 parts) Fresh orange juice",
      "1 cl (1 part) Fresh cream",
    ],
  },
  {
    title: "Grasshopper",
    image: "/wiki/File:Grasshopper_cocktail.jpg",
    type: "Cocktail",
    served: "up",
    preparation:
      "Pour ingredients into a cocktail shaker with ice. Shake briskly and then strain into a chilled cocktail glass.",
    timing: "After dinner",
    category: "Contemporary Classics",
    src: "/wiki/Grasshopper_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Crème de cacao", "Crème de menthe"],
    ingredients: [
      "3 cl Crème de menthe (green)",
      "3 cl Crème de cacao (white)",
      "3 cl cream",
    ],
  },
  {
    title: "Hemingway Special",
    image: "/wiki/File:Hemingway_Daiquiri.jpg",
    type: "Mixed drink",
    served: "Straight up; without ice",
    preparation: "Pour all ingredients into a shaker with ice. Shake.",
    timing: "All day",
    category: "Contemporary Classics",
    src: "/wiki/Hemingway_Special",
    drinkware: "Cocktail glass",
    alcohol: ["Rum"],
    ingredients: [
      "6 cL (12 parts) Rum",
      "4 cl (8 parts) grapefruit juice",
      "1.5 cL (3 parts) Maraschino liqueur",
      "1.5 cl (3 parts) fresh lime juice",
    ],
  },
  {
    title: "Horse's Neck",
    image: "/wiki/File:Horse%27s_Neck_cocktail.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Long spiral of lemon zest",
    preparation:
      "Pour brandy and ginger ale directly into highball glass with ice cubes. Stir gently. Garnish with lemon zest. If desired, add dashes of Angostura Bitter.",
    category: "Contemporary Classics",
    src: "/wiki/Horse%27s_Neck",
    drinkware: "Highball glass",
    alcohol: ["Brandy"],
    ingredients: [
      "4 cL (1 part) Brandy",
      "12 cL (3 parts) Ginger ale",
      "Dash of Angostura bitter (optional)",
    ],
  },
  {
    title: "Irish Coffee",
    image: "/wiki/File:Irish_coffee_glass.jpg",
    type: "Mixed drink",
    served: "Hot",
    preparation:
      "Heat the coffee, whiskey and sugar; do not boil. Pour into glass and top with cream; serve hot.",
    category: "Contemporary Classics",
    src: "/wiki/Irish_coffee",
    drinkware: "Irish coffee mug",
    alcohol: ["Irish whiskey"],
    ingredients: [
      "4 cl (2 parts) Irish whiskey",
      "8 cl (4 parts) hot coffee",
      "3 cl (1½ parts) fresh cream",
      "1 tsp brown sugar",
    ],
  },
  {
    title: "Kir",
    image: "/wiki/File:Kir_cocktail.jpg",
    type: "Wine cocktail",
    served: "Straight up; without ice",
    preparation:
      "Add the crème de cassis to the bottom of the glass, then top up with wine.",
    timing: "Before Dinner",
    notes:
      "A recipe can be found at the International Bartenders Association website.",
    category: "Contemporary Classics",
    src: "/wiki/Kir_(cocktail)",
    drinkware: "Wine glass (white)",
    alcohol: ["Wine"],
    ingredients: ["9 cl (9 parts) white wine", "1 cl (1 part) crème de cassis"],
  },
  {
    title: "Long Island Iced Tea",
    image: "/wiki/File:Long_Island_Iced_Teas.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "lemon slice",
    preparation:
      "Add all ingredients into highball glass filled with ice. Stir gently. Optionally garnish with lemon slice. [1]",
    category: "Contemporary Classics",
    src: "/wiki/Long_Island_iced_tea",
    drinkware: "Highball glass",
    alcohol: ["Gin", "Tequila", "Vodka", "Rum", "Triple sec"],
    ingredients: [
      "1.5 cl Tequila",
      "1.5 cl Vodka",
      "1.5 cl White rum",
      "1.5 cl Triple sec",
      "1.5 cl Gin",
      "2.5 cl Lemon juice",
      "3.0 cl simple syrup",
      "Top with Cola",
    ],
  },
  {
    title: "Mai Tai",
    image: "/wiki/File:Trader_Vic%27s_1944_Mai_Tai.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "spearmint leaves and lime shell",
    preparation:
      "Shake all ingredients with ice. Strain into glass. Garnish and serve with straw.",
    category: "Contemporary Classics",
    src: "/wiki/Mai_Tai",
    drinkware: "Old Fashioned glass",
    alcohol: ["Rum"],
    ingredients: [
      "3 cl amber Jamaican rum",
      "3 cl Martinique molasses rum",
      "1.5 cl orange curaçao",
      "1.5 cl orgeat syrup",
      "3 cl fresh lime juice",
      ".75 cl simple syrup",
    ],
  },
  {
    title: "Margarita",
    image: "/wiki/File:MargaritaReal.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Salt on the rim (optional)",
    preparation:
      "Pour all ingredients into shaker with ice. Shake well and strain into cocktail glass rimmed with salt.",
    timing: "All Day",
    category: "Contemporary Classics",
    src: "/wiki/Margarita",
    drinkware: "Margarita glass",
    alcohol: ["Tequila"],
    ingredients: [
      "5 cL (10 parts) Tequila",
      "2 cL (4 parts) Triple sec or Cointreau",
      "1.5 cL (3 parts) Lime juice",
    ],
  },
  {
    title: "Mimosa",
    image: "/wiki/File:Pool-side_Mimosas_at_The_Standard_Hotel.jpg",
    type: "Wine cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Orange twist",
    preparation:
      "Ensure both ingredients are well chilled, then mix into the glass. Serve cold.",
    category: "Contemporary Classics",
    src: "/wiki/Mimosa_(cocktail)",
    drinkware: "Champagne flute",
    alcohol: ["Champagne"],
    ingredients: ["7.5 cl champagne", "7.5 cl orange juice"],
  },
  {
    title: "Mint Julep",
    image: "/wiki/File:Mint_Julep_im_Silberbecher.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Mint sprig",
    preparation:
      "In a highball glass gently muddle the mint, sugar and water. Fill the glass with cracked ice, add Bourbon and stir well until the glass is well frosted. Garnish with a mint sprig.",
    category: "Contemporary Classics",
    src: "/wiki/Mint_julep",
    drinkware: "Highball glass",
    alcohol: ["Bourbon whiskey"],
    ingredients: [
      "6 cL Bourbon whiskey",
      "4 mint leaves",
      "1 teaspoon powdered sugar",
      "2 teaspoons water",
    ],
  },
  {
    title: "Mojito",
    image: "/wiki/File:Mojito98775.jpeg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish":
      "sprig of mint (Yerba buena in the original recipe), slice of lime",
    preparation:
      "Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish with sprig of mint leaves and lemon slice. Serve with straw.",
    category: "Contemporary Classics",
    src: "/wiki/Mojito",
    drinkware: "Collins glass",
    alcohol: ["Rum"],
    ingredients: [
      "4 cl white rum",
      "3 cl fresh lime juice",
      "6 sprigs of mint",
      "2 teaspoons sugar (or 2 cl of sugar syrup)",
    ],
  },
  {
    title: "Moscow mule",
    image: "/wiki/File:Moscow_Mule_at_Rye,_San_Francisco.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Lime slice",
    preparation:
      "Combine vodka and ginger beer in a highball glass filled with ice. Add lime juice. Stir gently. Garnish.",
    category: "Contemporary Classics",
    src: "/wiki/Moscow_mule",
    drinkware: "copper mug",
    alcohol: ["Vodka"],
    ingredients: [
      "4.5 cl (9 parts) vodka",
      "0.5 cl (1 part) lime juice",
      "12 cl (24 parts) ginger beer",
    ],
  },
  {
    title: "Piña Colada",
    image: "/wiki/File:Pi%C3%B1a_Colada.jpg",
    type: "Mixed drink",
    served: "Blended with ice (frozen style)",
    "standard-garnish": "Pineapple slice and/or maraschino cherry",
    preparation:
      "Blend all the ingredients with ice in an electric blender, pour into a large goblet or Hurricane glass and serve.",
    category: "Contemporary Classics",
    src: "/wiki/Pi%C3%B1a_Colada",
    drinkware: "Poco Grande glass",
    alcohol: ["Rum"],
    ingredients: [
      "50 ml White Rum",
      "30 ml Coconut Cream",
      "50 ml Fresh Pineapple Juice",
    ],
  },
  {
    title: "Pisco Sour",
    image: "/wiki/File:Pisco_sour_20100613b.JPG",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Angostura bitters (1 dash)",
    preparation:
      "Vigorously shake contents in a cocktail shaker with ice cubes, then strain into a glass and garnish with bitters.[1]",
    timing: "All day",
    category: "Contemporary Classics",
    src: "/wiki/Pisco_Sour",
    drinkware: "Old Fashioned glass",
    alcohol: ["Pisco"],
    ingredients: [
      "60ml Pisco",
      "30ml lime juice",
      "20ml simple syrup",
      "1 egg white",
      "Several drops of aromatic bitters at the end",
    ],
  },
  {
    title: "Sea Breeze",
    image: "/wiki/File:Cocktail_with_vodka.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "lime slice",
    preparation:
      "Build all ingredients in a highball glass filled with ice. Garnish with lime wedge.",
    category: "Contemporary Classics",
    src: "/wiki/Sea_Breeze_(cocktail)",
    drinkware: "Highball glass",
    alcohol: ["Vodka"],
    ingredients: [
      "4 cl Vodka",
      "12 cl Cranberry juice",
      "3 cl Grapefruit juice",
    ],
  },
  {
    title: "Sex on the Beach",
    image: "/wiki/File:Question_book-new.svg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "orange slice",
    preparation:
      "Build all ingredients in a highball glass filled with ice. Garnish with orange slice.",
    category: "Contemporary Classics",
    src: "/wiki/Sex_on_the_Beach",
    drinkware: "Highball glass",
    alcohol: ["Vodka"],
    ingredients: [
      "4 cl Vodka",
      "2 cl Peach schnapps",
      "4 cl Orange juice",
      "4 cl cranberry juice",
    ],
  },
  {
    title: "Singapore Sling",
    image: "/wiki/File:Singaporesling-march2017.jpg",
    type: "Mixed drink",
    served: "Straight up; without ice",
    "standard-garnish": "Maraschino cherry, pineapple",
    preparation:
      "Pour all ingredients into cocktail shaker filled with ice cubes. Shake well. Strain into highball glass. Garnish with pineapple and cocktail cherry.",
    category: "Contemporary Classics",
    src: "/wiki/Singapore_Sling",
    drinkware: "Hurricane glass",
    alcohol: ["Gin"],
    ingredients: [
      "3 cl gin",
      "1.5 cl cherry liqueur (cherry brandy)",
      "0.75 cl Cointreau",
      "0.75 cl DOM Bénédictine",
      "1 cl Grenadine",
      "12 cl pineapple juice",
      "1.5 cl fresh lime juice",
      "1 dash Angostura bitters",
    ],
  },
  {
    title: "Tequila sunrise",
    image: "/wiki/File:Tequila_Sunrise_glass.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "orange slice and cherry",
    preparation:
      "Pour the tequila and orange juice into glass over ice. Add the grenadine, which will sink to the bottom. Stir gently to create the sunrise effect. Garnish and serve.",
    category: "Contemporary Classics",
    src: "/wiki/Tequila_Sunrise_(cocktail)",
    drinkware: "Collins glass",
    alcohol: ["Tequila"],
    ingredients: [
      "4.5 cl (3 parts) Tequila",
      "9 cl (6 parts) Orange juice",
      "1.5 cl (1 part) Grenadine syrup",
    ],
  },
  {
    title: "Vesper",
    image: "/wiki/File:Gordon%27s_Vesper.jpeg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "lemon twist",
    preparation:
      "Shake and strain into a chilled cocktail glass. Add the garnish.",
    timing: "Before dinner",
    category: "Contemporary Classics",
    src: "/wiki/Vesper_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: ["4.5 cl gin", "1.5 cl vodka", "0.75 cl Lillet Blanc"],
  },
  {
    title: "Zombie",
    image: "/wiki/File:ZombieCocktail.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "mint sprig",
    preparation:
      "Mix ingredients in a shaker with crushed ice. Pour into a tall tumbler glass.",
    notes:
      "Because of the high proof rum, this cocktail could be lit if desired.",
    category: "Contemporary Classics",
    src: "/wiki/Zombie_(cocktail)",
    drinkware: "Zombie glass",
    alcohol: ["Rum"],
    ingredients: [
      "45 ml Jamaican dark rum",
      "45 ml Puerto Rican gold rum",
      "30 ml Demerara rum",
      "20 ml fresh lime juice",
      "15 ml falernum",
      "15 ml Donn’s Mix (2 parts fresh yellow grapefruit and 1 part cinnamon syrup)",
      "1 tsp Grenadine syrup",
      "1 dash Angostura bitters",
      "6 drops Pernod",
    ],
  },
  {
    title: "Barracuda",
    image: "/wiki/File:Barracuda_Sparkling_Cocktail.png",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Shake pour ingredients with ice. Strain into glass, top with Sparkling wine.",
    category: "New Era",
    src: "/wiki/Barracuda_(cocktail)",
    drinkware: "Margarita glass",
    alcohol: ["Rum"],
    ingredients: [
      "4.5 cl Gold rum",
      "1.5 cl Galliano",
      "6 cl Pineapple juice",
      "1 dash fresh lime juice",
      "Top with Prosecco",
    ],
  },
  {
    title: "Bee's Knees",
    image: "/wiki/File:Bee%27s_Knees_(cocktail).jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "lemon peel",
    preparation:
      "Shake with ice and strain into a chilled large cocktail glass",
    category: "New Era",
    src: "/wiki/Bee%27s_Knees_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: ["2 oz gin", "3/4 oz lemon juice", "3/4 oz honey"],
  },
  {
    title: "Bramble",
    image: "/wiki/File:Bramble_Cocktail1.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Blackberry, lemon slice",
    preparation:
      "Fill glass with crushed ice. Build gin, lemon juice and simple syrup over. Stir, and then pour blackberry liqueur over in a circular fashion to create marbling effect. Garnish with two blackberries and lemon slice.",
    timing: "All Day",
    category: "New Era",
    src: "/wiki/Bramble_(cocktail)",
    drinkware: "Old Fashioned glass",
    alcohol: ["Gin"],
    ingredients: [
      "5 cl gin",
      "2.5 cl lemon juice",
      "1.25 cl simple syrup",
      "1.5 cl Creme de Mure (blackberry liqueur)",
    ],
  },
  {
    title: "Canchanchara",
    image: "/wiki/File:Canchanchara.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Lime wedge",
    preparation:
      "Mix honey with water and lime juice and spread the mixture on the bottom and sides of the glass. Add cracked ice, and then the rum. End by energetically stirring from bottom to top.",
    category: "New Era",
    src: "/wiki/Canchanchara",
    drinkware: "Old Fashioned glass",
    alcohol: ["Rum"],
    ingredients: [
      "6 cl rum (Cuban aguardiente)",
      "1.5 cl fresh lime juice",
      "1.5 cl raw honey",
      "5 cl water",
    ],
  },
  {
    title: "Dark 'n' Stormy",
    image: "/wiki/File:DarknStormy.jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Lime wedge",
    preparation:
      "Fill glass with ice, add rum and top with ginger beer. Garnish with lime wedge.",
    category: "New Era",
    src: "/wiki/Dark_%27n%27_Stormy",
    drinkware: "Highball glass",
    alcohol: ["Rum"],
    ingredients: ["6 cl dark rum", "10 cl ginger beer"],
  },
  {
    title: "Espresso martini",
    image:
      "/wiki/File:Bistrot_Bruno_Loubet,_Clerkenwell,_London_(4574785649).jpg",
    type: "Mixed drink",
    served: "Straight up; without ice",
    "standard-garnish": "3 coffee beans",
    preparation:
      "Pour ingredients into shaker filled with ice, shake vigorously, and strain into chilled martini glass.",
    category: "New Era",
    src: "/wiki/Espresso_martini",
    drinkware: "Cocktail glass",
    alcohol: ["Vodka"],
    ingredients: [
      "5 cl vodka",
      "3 cl Kahlúa",
      "Sugar syrup (according to individual preference of sweetness)",
      "1 strong espresso",
    ],
  },
  {
    title: "Fernandito",
    image: "/wiki/File:Fernet_and_Coke_(Fernet_con_Coca).jpg",
    type: "Mixed drink",
    served: "On the rocks; poured over ice",
    preparation:
      "Fill a double old-fashioned glass with ice. Pour in the Fernet-Branca, fill the glass with cola. Stir gently.",
    category: "New Era",
    src: "/wiki/Fernandito",
    drinkware: "Old Fashioned glass",
    alcohol: ["Fernet-Branca"],
    ingredients: ["5 cl Fernet-Branca", "Cola to top up"],
  },
  {
    title: "French martini",
    image: "/wiki/File:Question_book-new.svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour all ingredients into shaker with ice cubes. Shake well and strain into a chilled cocktail glass. Squeeze oil from lemon peel onto the drink.",
    timing: "Before dinner",
    category: "New Era",
    src: "/wiki/French_martini",
    drinkware: "Cocktail glass",
    alcohol: ["Vodka", "Raspberry liqueur"],
    ingredients: [
      "4.5 cl vodka",
      "1.5 cl Raspberry Liqueur",
      "1.5 cl fresh pineapple juice",
    ],
  },
  {
    title: "Illegal",
    image: "/wiki/File:Cocktail_Glass_(Martini).svg",
    type: "Cocktail",
    served:
      "Served in one of two ways:\nStraight up (no ice) in a chilled cocktail glass\nOn the rocks (over ice) in a traditional clay or terracotta mug",
    preparation:
      'Pour all ingredients into shaker with ice cubes. Shake vigorously. Strain into chilled cocktail glass, or "on the rocks" into a traditional clay or terracotta mug.',
    category: "New Era",
    src: "/wiki/Illegal_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Mezcal"],
    ingredients: [
      "3 cl Mezcal (espadín)",
      "1.5 cl Jamaica overproof white rum",
      "1.5 cl Falernum liqueur",
      "1 barspoon maraschino Luxardo",
      "2.25 cl fresh lime juice",
      "1.5 cl simple syrup",
      "Few drops of egg white (optional)",
    ],
  },
  {
    title: "Lemon Drop Martini",
    image: "/wiki/File:Lemon_Drop_cocktails.jpg",
    type: "Mixed drink",
    served: "Straight up; without ice",
    "standard-garnish": "Lemon slice",
    preparation:
      "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass. Garnish with sugar rim around the glass.",
    timing: "All Day",
    category: "New Era",
    src: "/wiki/Lemon_drop_martini",
    drinkware: "Cocktail glass",
    alcohol: ["Vodka"],
    ingredients: ["3 cl vodka citron", "2 cl triple sec", "1.5 cl lemon juice"],
  },
  {
    title: "Naked and Famous",
    image: "/wiki/File:Cocktail_Glass_(Martini).svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass.",
    category: "New Era",
    src: "/wiki/Naked_and_Famous_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Mezcal"],
    ingredients: [
      "2.25 cl mezcal",
      "2.25 cl yellow Chartreuse",
      "2.25 cl Aperol",
      "2.25 cl fresh lime juice",
    ],
  },
  {
    title: "New York Sour",
    image: "/wiki/File:New_York_Sour.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Lemon or orange zest and cherry",
    preparation:
      "Pour the whiskey, syrup, lemon juice, and egg white into shaker with ice cubes. Shake vigorously. Strain into chilled rocks glass filled with ice. Float the wine on top. Garnish with lemon or orange zest and cherry.",
    category: "New Era",
    src: "/wiki/New_York_Sour",
    drinkware: "Rocks glass",
    alcohol: ["Whiskey"],
    ingredients: [
      "6 cl whiskey (rye or bourbon)",
      "2.25 cl Simple syrup",
      "3 cl fresh lemon juice",
      "Few drops of egg white",
      "1.5 cl red wine (Shiraz or Malbec)",
    ],
  },
  {
    title: "Old Cuban",
    image: "/wiki/File:VTR_-_The_%22Old_Cuban%22_(6038903420).jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Mint sprigs",
    preparation:
      "Pour all ingredients except the wine into cocktail shaker, shake well with ice, strain into chilled elegant cocktail glass. Top up with the sparkling wine and garnish with mint sprigs",
    category: "New Era",
    src: "/wiki/Old_Cuban",
    drinkware: "Cocktail glass",
    alcohol: ["Rum"],
    ingredients: [
      "4.5 cl aged rum",
      "2.25 cl fresh lime juice",
      "3 cl simple syrup",
      "2 dashes Angostura bitters",
      "6 to 8 mint leaves",
      "6 cl champagne brut or Prosecco",
    ],
  },
  {
    title: "Paloma",
    image: "/wiki/File:TequilaPaloma.JPG",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "lime wedge",
    preparation: "Stir together and serve over ice.",
    category: "New Era",
    src: "/wiki/Paloma_(cocktail)",
    drinkware: "Highball glass",
    alcohol: ["Tequila"],
    ingredients: ["One part tequila", "Three parts grapefruit soda"],
  },
  {
    title: "Paper Plane",
    image: "/wiki/File:Cocktail_Glass_(Martini).svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.",
    category: "New Era",
    src: "/wiki/Paper_Plane_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Bourbon whiskey"],
    ingredients: [
      "3 cl Bourbon whiskey",
      "3 cl amaro Nonino",
      "3 cl Aperol",
      "3 cl fresh lemon juice",
    ],
  },
  {
    title: "Penicillin",
    image: "/wiki/File:The_Spotted_Owl_-_Penicillin.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Candied ginger",
    preparation:
      "Muddle fresh ginger in a shaker and add the remaining ingredients, except for the Lagavulin whiskey. Fill the shaker with ice and shake. Double-strain into a chilled old fashioned glass with ice. Float the Lagavulin whiskey on top.",
    category: "New Era",
    src: "/wiki/Penicillin_(cocktail)",
    drinkware: "Old Fashioned glass",
    alcohol: ["Whiskey"],
    ingredients: [
      "6 cl blended Scotch whiskey",
      "0.75 cl Lagavulin 16y whiskey",
      "2.25 cl fresh lemon juice",
      "2.25 cl honey syrup",
      "2-3 quarter-sized slices of fresh ginger",
    ],
  },
  {
    title: "Russian Spring Punch",
    image: "/wiki/File:Russian_spring_punch.jpg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    preparation:
      "Pour all ingredients into cocktail shaker except the sparkling wine, shake well with ice, strain into chilled tall tumbler glass filled with ice and top up with sparkling wine.",
    category: "New Era",
    src: "/wiki/Russian_Spring_Punch",
    drinkware: "Highball glass",
    alcohol: ["Vodka"],
    ingredients: [
      "2.5 cl Vodka",
      "1.5 cl Crème de cassis",
      "1 cl Sugar Syrup",
      "2.5 cl Lemon Juice, fresh",
    ],
  },
  {
    title: "South Side or Southside",
    image: "/wiki/File:Wikibooks-logo.svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "mint leaf",
    preparation:
      "Shake with ice and strain into a chilled large cocktail glass",
    notes: "A variant, the Southside Fizz, adds soda water and ice.",
    category: "New Era",
    src: "/wiki/Southside_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Gin"],
    ingredients: [
      "2 oz gin",
      "1 oz lime juice",
      "3/4 oz simple syrup",
      "1 sprig mint",
      "1 fresh mint leaf[1]",
    ],
  },
  {
    title: "Spicy Fifty",
    image: "/wiki/File:Cocktail_Glass_(Martini).svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Red chili pepper",
    preparation:
      "Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.",
    category: "New Era",
    src: "/wiki/Spicy_Fifty",
    drinkware: "Cocktail glass",
    alcohol: ["Vodka"],
    ingredients: [
      "5 cl vodka vanilla",
      "1.5 cl elderflower cordial",
      "1.5 cl fresh lemon juice",
      "1 cl Monin honey syrup",
      "2 thin slices red chili pepper",
    ],
  },
  {
    title: "Spritz Veneziano",
    image: "/wiki/File:20120704_170702_venezia_1584.jpg",
    type: "Wine cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Slice of Orange",
    preparation:
      "Build all ingredients into a wine glass filled with ice. Stir gently.",
    category: "New Era",
    src: "/wiki/Spritz_Veneziano",
    drinkware: "Aperol Spritz Glass / Wine Glass[1]",
    alcohol: ["Prosecco"],
    ingredients: ["9 cl Prosecco", "6 cl Aperol", "Splash of soda water"],
  },
  {
    title: "Tipperary",
    image: "/wiki/File:Cocktail_Glass_(Martini).svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    "standard-garnish": "Orange slice",
    preparation:
      "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled cocktail glass. Garnish with a slice of orange.",
    category: "New Era",
    src: "/wiki/Tipperary_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Irish whiskey"],
    ingredients: [
      "5 cl Irish whiskey",
      "2.5 cl sweet red vermouth",
      "1.5 cl green Chartreuse",
      "2 dashes Angostura bitters",
    ],
  },
  {
    title: "Tommy's margarita",
    image: "/wiki/File:TommysMargarita.jpg",
    type: "Mixed drink",
    served: "Straight (except at Tommy's)",
    preparation: "Shake and strain into a chilled cocktail glass.",
    timing: "All Day",
    category: "New Era",
    src: "/wiki/Tommy%27s_margarita",
    drinkware: "Cocktail glass",
    alcohol: ["Tequila"],
    ingredients: [
      "4.5 cl Tequila",
      "1.5 cl Freshly squeezed lime juice",
      "2 bar spoons of agave nectar",
    ],
  },
  {
    title: "Trinidad Sour",
    image: "/wiki/File:VTR_-_Trinidad_Sour_(18045674468).jpg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled cocktail glass.",
    category: "New Era",
    src: "/wiki/Trinidad_Sour",
    drinkware: "Cocktail glass",
    alcohol: ["Angostura bitters"],
    ingredients: [
      "4.5 cl Angostura bitters",
      "3 cl orgeat syrup",
      "2.25 cl fresh lemon juice",
      "1.5 cl rye whiskey",
    ],
  },
  {
    title: "Ve.n.to",
    image: "/wiki/File:Question_book-new.svg",
    type: "Cocktail",
    served: "On the rocks; poured over ice",
    "standard-garnish": "Lemon zest and white grapes",
    preparation:
      "Pour all ingredients into the shaker. Shake vigorously with ice. Strain into a chilled small tumbler glass filled with ice.",
    notes:
      "If desired, the water used to make the honey mix can be replaced by chamomile infusion.",
    category: "New Era",
    src: "/wiki/Ve.n.to",
    drinkware: "tumbler",
    alcohol: ["Grappa"],
    ingredients: [
      "4.5 cl white smooth grappa",
      "2.25 cl fresh lemon juice",
      "1.5 cl honey mix (made with chamomile infusion if desired)",
      "1.5 cl chamomile cordial",
      "1 cl egg white (optional)",
    ],
  },
  {
    title: "Yellow Bird",
    image: "/wiki/File:Cocktail_Glass_(Martini).svg",
    type: "Cocktail",
    served: "Straight up; without ice",
    preparation:
      "Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled cocktail glass.",
    timing: "All Day",
    category: "New Era",
    src: "/wiki/Yellow_Bird_(cocktail)",
    drinkware: "Cocktail glass",
    alcohol: ["Rum"],
    ingredients: [
      "3 cl White Rum",
      "1.5 cl Galliano",
      "1.5 cl Triple sec",
      "1.5 cl Lime juice",
    ],
  },
];
